### ISSUE TITLE
zone.js:101 GET http://localhost:3000/ng2-fullpage 404 (Not Found)

### ISSUE THREAD

**Issue by neilhoff** [meiblorn/ng2-fullpage#4]
I started an Angular 2 app using the [5 Minute Quickstart](https://angular.io/docs/ts/latest/quickstart.html) which uses SystemJS instead of WebPack.

Then I added in ng2-fullpage.

When I startup and navigate to the site I am getting this error:
_zone.js:101 GET http://localhost:3000/ng2-fullpage 404 (Not Found)_

![image](https://cloud.githubusercontent.com/assets/1918319/15454812/3e4c3828-2008-11e6-9359-bb58280fad60.png)

**package.json**

    {
      "name": "angular2-quickstart",
      "version": "1.0.0",
      "scripts": {
        "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
        "lite": "lite-server",
        "postinstall": "typings install",
        "tsc": "tsc",
        "tsc:w": "tsc -w",
        "typings": "typings"
      },
      "license": "ISC",
      "dependencies": {
        "@angular/common": "2.0.0-rc.1",
        "@angular/compiler": "2.0.0-rc.1",
        "@angular/core": "2.0.0-rc.1",
        "@angular/http": "2.0.0-rc.1",
        "@angular/platform-browser": "2.0.0-rc.1",
        "@angular/platform-browser-dynamic": "2.0.0-rc.1",
        "@angular/router": "2.0.0-rc.1",
        "@angular/router-deprecated": "2.0.0-rc.1",
        "@angular/upgrade": "2.0.0-rc.1",
        "angular2-in-memory-web-api": "0.0.7",
        "bootstrap": "^3.3.6",
        "es6-shim": "^0.35.0",
        "jquery": "2.2.4",
        "ng2-fullpage": "^1.2.1",
        "reflect-metadata": "^0.1.3",
        "rxjs": "5.0.0-beta.6",
        "systemjs": "0.19.27",
        "zone.js": "^0.6.12"
      },
      "devDependencies": {
        "concurrently": "^2.0.0",
        "lite-server": "^2.2.0",
        "typescript": "^1.8.10",
        "typings": "^0.8.1"
      }
    }

**app.components.ts**

    import { Component } from '@angular/core';
    import {FullpageDirective} from 'ng2-fullpage';

    @Component({
        selector: 'my-app',
        directives: [FullpageDirective],
        template:  `
            <div >
                <div class="section"> Some section 1 </div>
                    <div class="section"> Some section 2 </div>
                    <div class="section">
                        <div class="slide"> Slide 1 </div>
                        <div class="slide"> Slide 2 </div>
                        <div class="slide"> Slide 3 </div>
                        <div class="slide"> Slide 4 </div>
                    </div>
                <div class="section"> Some section 4 </div>
            </div>
        `
    })
    export class AppComponent { }

Any ideas on what is wrong?

Thank you for porting this to Angular 2!

**Comment by neilhoff** [comment]
I was able to get a little further by adding:

    'ng2-fullpage':               'node_modules/ng2-fullpage/ng2-fullpage.js'

to the `var  map = {` section of _systemjs.config.js_ file.

Now I get this error in Chrome dev tools:
_zone.js:101 GET http://localhost:3000/node_modules/ng2-fullpage/components/ 404 (Not Found)_


**systemjs.config.js**

    /**
     * PLUNKER VERSION (based on systemjs.config.js in angular.io)
     * System configuration for Angular 2 samples
     * Adjust as necessary for your application needs.
     */
    (function(global) {
  
      var ngVer = '@2.0.0-rc.1'; // lock in the angular package version; do not let it float to current!
  
      //map tells the System loader where to look for things
      var  map = {
        'app':                        'app',
  
        '@angular':                   'https://npmcdn.com/@angular', // sufficient if we didn't pin the version
        'angular2-in-memory-web-api': 'https://npmcdn.com/angular2-in-memory-web-api', // get latest
        'rxjs':                       'https://npmcdn.com/rxjs@5.0.0-beta.6',
        'ts':                         'https://npmcdn.com/plugin-typescript@4.0.10/lib/plugin.js',
        'typescript':                 'https://npmcdn.com/typescript@1.8.10/lib/typescript.js',
        'ng2-fullpage':               'node_modules/ng2-fullpage/ng2-fullpage.js'
      };
  
      //packages tells the System loader how to load when no filename and/or no extension
      var packages = {
        'app':                        { main: 'main.ts',  defaultExtension: 'ts' },
        'rxjs':                       { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { defaultExtension: 'js' }
      };
  
      var ngPackageNames = [
        'common',
        'compiler',
        'core',
        'http',
        'platform-browser',
        'platform-browser-dynamic',
        'router',
        'router-deprecated',
        'upgrade',
      ];
  
      // Add map entries for each angular package
      // only because we're pinning the version with `ngVer`.
      ngPackageNames.forEach(function(pkgName) {
        map['@angular/'+pkgName] = 'https://npmcdn.com/@angular/' + pkgName + ngVer;
      });
  
      // Add package entries for angular packages
      ngPackageNames.forEach(function(pkgName) {
  
        // Bundled (~40 requests):
        packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  
        // Individual files (~300 requests):
        //packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
      });
  
      var config = {
        // DEMO ONLY! REAL CODE SHOULD NOT TRANSPILE IN THE BROWSER
        transpiler: 'ts',
        typescriptOptions: {
          tsconfig: true
        },
        meta: {
          'typescript': {
            "exports": "ts"
          }
        },
        map: map,
        packages: packages
      }
  
      System.config(config);
  
    })(this);
  
  
    /*
     Copyright 2016 Google Inc. All Rights Reserved.
     Use of this source code is governed by an MIT-style license that
     can be found in the LICENSE file at http://angular.io/license
     */

**Comment by meiblorn** [comment]
@neilhoff, I've reproduced your issue and currently working on it. Thank you.

**Comment by meiblorn** [comment]
@neilhoff, the root cause was that system.js doesn't understand 'index' imports.

For example, it understands  
`import from './components/index'`, 
but doesn't understand 
`import from './components'` 
because it tries to find out './component.js' file insteand of './component/index.js' file.

I suppose, I will merge fix in 1 hour. Thank you very much!

**Comment by meiblorn** [comment]
@neilhoff, have some troubles. I will finish it up tomorrow.

**Comment by meiblorn** [comment]
Fixed in release-1.5.0. 

Here is example of system.js configuration (don't forget to install jquery typings):

```javascript
/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function(global) {
    // map tells the System loader where to look for things
    var map = {
        'app':                        'app', // 'dist',
        '@angular':                   'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs':                       'node_modules/rxjs',
        'jquery':                     'node_modules/ng2-fullpage/node_modules/jquery/dist/jquery.js',
        'fullpage.js':                'node_modules/ng2-fullpage/node_modules/fullpage.js/jquery.fullPage.js',
        'ng2-fullpage':               'node_modules/ng2-fullpage'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app':                        { main: 'main.js',  defaultExtension: 'js' },
        'rxjs':                       { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { defaultExtension: 'js' },
        'ng2-fullpage':               { main: 'ng2-fullpage.js', defaultExtension: 'js' }
    };
    var ngPackageNames = [
        'common',
        'compiler',
        'core',
        'http',
        'platform-browser',
        'platform-browser-dynamic',
        'router',
        'router-deprecated',
        'upgrade'
    ];
    // Add package entries for angular packages
    ngPackageNames.forEach(function(pkgName) {
        packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
    });
    var config = {
        map: map,
        packages: packages
    };

    System.config(config);
})(this);
```

**Comment by agyrafa** [comment]
I did all this steps too and my console still shows an error

`GET http://localhost:3000/fullpage.js 404 (Not Found)`

do you have any idea?
